### ISSUE TITLE
serde generates empty options field with Message Descriptors 

### ISSUE THREAD

**Issue by tardyp** [andrewhickman/prost-reflect#124]
Hello,

Trying to switch from protoc to protox, I see that some options are not properly parsed in some of my complicated protobuf files.

Digging a little bit more, I found that protox compare.rs tests rely on prost-reflect serde to compare results from protoc, but prost-reflect does not actually output anything for options.

This is a first issue to fix the test infrastructure, so that I can understand which case exactly protox fails to parse

**Comment by tardyp** [comment]
Thanks for your fix in protox test suite.

I am running protox via a python binding that I created. I cannot share my test proto as there are still confidential, so I wanted to try to dig a bit more. In most of my files, the options are properly parsed, but a few of them are not.
It's not obvious why, and I wanted to try to build a repro in your protox test suite then I realized the bug in the compare.rs stuff as the yaml did not output any option information.

I suspect that the CI failing on https://github.com/andrewhickman/protox/pull/72 is probably my bug. I'll try to dig a bit more on this.

**Comment by andrewhickman** [comment]
I believe the failure in the protox ci is related to use of the obsolete message set format - is that something you are using?

prost-reflect doesn't support message set, so I have been pondering whether to add support for it, or just cut that one property out of the test.

**Comment by tardyp** [comment]
I couldn't reproduce my issue into the test framework. the options were properly compiled.

My original issue is because my python wrapper did go through the compile() function, which uses file_descriptor_set() which goes through the prost conversion.

if I switch to Compiler() api and use encode_file_descriptor_set(), then my options are properly kept.

I'm finishing my python wrapper to protox. do you want me to contribute it in your protox repo (similar to https://github.com/tardyp/rs-bp/) , or should I keep it in github.com/tardyp/protoxy ?

**Comment by andrewhickman** [comment]
Glad you got it working!

I think python bindings are best left out-of-tree, but I'd be happy to link to your repo in the README, it sounds useful
