### ISSUE TITLE
Floating point values do not round-trip exactly

### ISSUE THREAD

**Issue by andrew-otiv** [andrewhickman/prost-reflect#129]
Floating point values are not round-tripping through JSON without precision loss... this is the one I hit (deep in a datastructure while "fuzzing"):

-4.4737164812014446e192
-4.473716481201445e192

Most use cases probably don't care, but it would make testing easier to not have edge cases that don't quite round trip. I thought the standard library's printers round-tripped...

Maybe this is something that can be configured to be stricter in serde?

Thanks for the free library!

**Comment by andrew-otiv** [comment]
OK, so maybe this is for serde::json... seems like it's know that the float conversions aren't perfect.

https://github.com/serde-rs/json/issues/130

**Comment by andrewhickman** [comment]
Yes, this is something I hit while testing this library too. Have you tried using the `float_roundtrip` feature of `serde_json` ?
