### ISSUE TITLE
Define a global DescriptorPool instance

### ISSUE THREAD

**Issue by andrewhickman** [andrewhickman/prost-reflect#13]
This would be used as a standard place to store descriptors for `ReflectMessage` implementations for well-known types, and implementations generated by `prost-reflect-build`.

**Comment by manassarpatwar** [comment]
+1

**Comment by andrewhickman** [comment]
Included in version [0.11.0](https://docs.rs/prost-reflect/latest/prost_reflect/struct.DescriptorPool.html#impl-DescriptorPool-1)
