### ISSUE TITLE
API for unknown fields

### ISSUE THREAD

**Issue by andrewhickman** [andrewhickman/prost-reflect#15]
Currently `DynamicMessage` stores unknown fields internally and roundtrips them through the byte representation, but there is no API to inspect them.

**Comment by 124C41p** [comment]
Would it be possible without much effort to add functions for getting/setting all unknown fields at once as a single `Vec<u8>` (at least temporarily unless you come up with something more general)?

Background: I am currently in the progress of creating an extension module for [python-betterproto](https://github.com/danielgtaylor/python-betterproto)  based on `prost-reflect` for improving (de-)serialization performance (see [this PR](https://github.com/danielgtaylor/python-betterproto/pull/520)). For that purpose, I need to be able to convert between your `DynamicMessage` and their `betterproto.Message` (including unknown fields).

**Comment by andrewhickman** [comment]
I had hoped prost would gain support for unknown fields that we could re-use here.

However if there's a real-world need for it, I'm happy to expose some new APIs for this. Would the APIs in #52 be sufficient for your usecase?

**Comment by 124C41p** [comment]
Regarding the level of detail this is perfect (even more than I need). However, I'll also need a function to set the unknown fields for conversion of `betterproto.Message` into `DynamicMessage` (maybe `.push_unknown(&mut self, ...)`?). Also (as mentioned in #50)  it would be really nice to have a destructive iterator like `pub fn take_unknown_fields(&mut self) -> impl Iterator<Item = UnknownField>` to avoid cloning on conversion.

Thanks a lot for starting this PR!

**Comment by andrewhickman** [comment]
What format are the unknown fields from `betterproto.Message` in? If they are just bytes, then I think `DynamicMessage::merge` or `DynamicMessage::merge_field` should be suffcient to add them into the message. 

A `push_unknown` function would need to do something in the error case when a field with the given number exists, which makes me hesitate to add it.

`take_unknown_fields` sounds like a reasonable companion to `take_fields` and `take_extensions`, I'll add that to the PR

**Comment by 124C41p** [comment]
Yes, I see. You are technically right. But when converting back and forth (`DynamicMessage` -> `betterproto.Message` -> `DynamicMessage`) this would mean a bit of unnecessary (de-)serialization, as I would have to call something like `msg.merge_field(num, tp, unknown_field.encode())` for each unknown field (I actually haven't found an encode method at first glance. How would I do this?)

Wouldn't it be nicer to have a function `DynamicField::set_unknown_field(&mut self, number: u32, wire_type: WireType, buf: &mut B) -> ...` with the same semantics but less overhead?

Anyway, it probably isn't actually that much of a deal, and I am very grateful that you are making this possible in the first place. So please go ahead as you feel most comfortable with.

**Comment by 124C41p** [comment]
If I am not mistaken, the current API `fn take_unknown(&mut self) -> impl Iterator<Item = UnknownField>` does not return the field number of the unknown fields, does it? This would be required for conversion.

**Comment by andrewhickman** [comment]
`UnknownField` includes the number

**Comment by andrewhickman** [comment]
> Yes, I see. You are technically right. But when converting back and forth (`DynamicMessage` -> `betterproto.Message` -> `DynamicMessage`) this would mean a bit of unnecessary (de-)serialization, as I would have to call something like `msg.merge(unknown_field.encode_field(num))` for each unknown field. Wouldn't it be nicer to have a function `DynamicField::set_unknown_field(&mut self, number: u32, wire_type: WireType, buf: &mut B) -> Result<(), DecodeError>` with the same semantics but less overhead?
> 
> Anyway, it probably isn't actually that much of a deal, and I am very grateful that you are making this possible in the first place. So please go ahead as you feel most comfortable with.

I've created an issue for a more extensive unknown fields API: #56 . I do agree that a proper setter function would be nicer, but I'd like to put some more thought into the API design.

**Comment by andrewhickman** [comment]
Version 0.11.5 is released with the new APIs
