### ISSUE TITLE
`FileDescriptor.dependencies` only iterates through public dependencies

### ISSUE THREAD

**Issue by b-camacho** [andrewhickman/prost-reflect#19]
# Background
[Public dependencies](https://developers.google.com/protocol-buffers/docs/proto#importing) are a protobuf feature for re-exporting symbols from different proto files, like [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/profile.proto#L6). The linked docs suggest this is meant for migrating between `.proto` file paths:

> By default, you can use definitions only from directly imported .proto files. However, sometimes you may need to move a .proto file to a  new location. Instead of moving the .proto file directly and updating all the call sites in a single change, you can put a placeholder .proto file in the old location to forward all the imports to the new location using the import public notion.

Notwithstanding, some repos seem to prefer `import public` over `import`, like [here](https://github.com/apple/coremltools/blob/main/mlmodel/format/Model.proto#L62) or [here](https://github.com/envoyproxy/envoy/blob/main/api/envoy/api/v2/cds.proto#L13).

# Current state
`FileDescriptor.dependencies` only lists [public dependencies](https://github.com/andrewhickman/prost-reflect/blob/main/prost-reflect/src/descriptor/mod.rs#L371).

# Proposed change
Perhaps `FileDescriptor.dependencies` should iterate through the entire dependencies list, as opposed to only the public dependencies?

I'm more than happy to make this change and put up a PR, just wondering if there's a reason for only listing public dependencies that I missed

**Comment by andrewhickman** [comment]
Wow, not sure what I was thinking when I named that method 😮. I agree that I'd expect it to iterate all the dependencies, public or otherwise.

I doubt this method is widely used, so I think we can just change the behaviour in the next major version along with a note in the changelog. Maybe the existing method should be renamed `public_dependencies()` as well

**Comment by andrewhickman** [comment]
I've made this change in version 0.10.0
