### ISSUE TITLE
Stream a repeated field without parsing entire structure

### ISSUE THREAD

**Issue by dnsco** [andrewhickman/prost-reflect#26]
On a project I work on there's an Message of 
```
message Log {
  repeated Packet packets = 1;
}
```
where packet is the internal structure that is moderately complex.

They're then dumping these logs to disk, but unfortunately some of these files are multiple gigabytes which makes them unwieldy to work with.

If I could iterate over Packets without paying the cost of deserialization up front things could be parallelized.

Poking around prost_reflect to see if there is a way to do this but not finding anything.

In any case, thanks for the great library!

**Comment by andrewhickman** [comment]
Hi!

I don't think this is directly possible with either prost or prost-reflect. But I think you can avoid buffering a whole message into memory using a custom `Message` implementation:

```
#[derive(Default, Debug)]
struct StreamingReader;

impl Message for StreamingReader {
    fn merge_field<B>(
        &mut self,
        tag: u32,
        wire_type: WireType,
        buf: &mut B,
        ctx: DecodeContext,
    ) -> Result<(), DecodeError>
    where
        B: Buf,
        Self: Sized,
    {
        if tag == 1 {
            prost::encoding::check_wire_type(WireType::LengthDelimited, wire_type)?;
            let packet = Packet::decode_length_delimited(buf)?;

            do_some_stuff(packet);

            Ok(())
        } else {
            prost::encoding::skip_field(wire_type, tag, buf, ctx)
        }
    }

    fn encode_raw<B>(&self, _: &mut B)
    where
        B: BufMut,
        Self: Sized,
    {
        unimplemented!()
    }


    fn encoded_len(&self) -> usize {
        unimplemented!()
    }

    fn clear(&mut self) {
        unimplemented!()
    }
}
```

**Comment by dnsco** [comment]
Thank you!

**Comment by dnsco** [comment]
This gets me what I need so I'm gonna close the issue, thanks so much for taking the time to help me, feel free to reopen if this winds up being something you want to support.
