### ISSUE TITLE
Support adding individual message/enum descriptors

### ISSUE THREAD

**Issue by manassarpatwar** [andrewhickman/prost-reflect#30]
Similar to #6 I would like to register messages to the descriptor pool

Also would love #13 to which I can register the messages. Am using protoregister package in go and trying to migrate to rust

**Comment by andrewhickman** [comment]
I think the best way to do this is just to add a FileDescriptorProto containing the message/enum type

```
let mut pool = DescriptorPool::new();
pool.add_file_descriptor_proto(FileDescriptorProto {
    name: "dummy.proto",
    package: "my.package",
    message_type: vec![DescriptorProto { 
        ... 
    }],
    ..Default::default()
});
```

otherwise what would `parent_file()` or `package_name()` return for the message descriptor?
