### ISSUE TITLE
Expose `Kind::wire_type`

### ISSUE THREAD

**Issue by slinkydeveloper** [andrewhickman/prost-reflect#33]
Hi,
I wonder if it's possible to expose `Kind::wire_type`. This is useful when dealing with manual parsing of protobuf.

**Comment by andrewhickman** [comment]
Seems reasonable to make this public. I think the only reason I didn't is that `WireType` doesn't appear in the public documentation for prost, but since its required to implement `Message` it should be OK to use.

I'd accept a PR to implement this.
