### ISSUE TITLE
Generate protobuf schema from a type that derives `ReflectMessage`

### ISSUE THREAD

**Issue by HKalbasi** [andrewhickman/prost-reflect#48]
Similar to how [schemars](https://docs.rs/schemars/latest/schemars/) generates json schemas from Rust structs. It seems unlike `prost::Message`, the `ReflectMessage` crate has the necessary ingredients for implementing such a feature. Do you think it is possible? And if so, do you consider it in scope for this project?

**Comment by andrewhickman** [comment]
I don't think that would be in scope for this project. However I think it should be possible to implement using the public API of MessageDescriptor - that's what is used for JSON serialization internally

**Comment by HKalbasi** [comment]
Thanks for quick response. I will try to implement it using `MessageDescriptor` and publish it as a separate crate.

**Comment by HKalbasi** [comment]
I looked at the api and wonder why `ReflectMessage::descriptor` needs `&self`? Isn't it something that could be derived from the type itself?

**Comment by andrewhickman** [comment]
It needs `&self` so it can be implemented for `DynamicMessage`. All message types generated by `prost-build` should have a cheap `Default` implementation, so its possible to get the descriptor from the type by doing `T::default().descriptor()`
