### ISSUE TITLE
Support FieldOptions

### ISSUE THREAD

**Issue by emakryo** [andrewhickman/prost-reflect#8]
Currently, prost-reflect does not seem to have `FieldOptions`, which hold options per field such as a deprecated flag.
It would be helpful when applications can use these `FieldOptions` dynamically.
(yes, I'm just writing a parser of protobuf text format with prost-reflect.)

**Comment by andrewhickman** [comment]
Hi @emakryo, I've published version 0.5.5 which includes a new method [`FieldDescriptor::field_descriptor_proto`](https://docs.rs/prost-reflect/0.5.5/prost_reflect/struct.FieldDescriptor.html#method.field_descriptor_proto) to allow accessing properties like `options` which aren't wrapped by a specific API.

**Comment by emakryo** [comment]
It looks like what I need. I will try it, thank you!

**Comment by emakryo** [comment]
Now that I have confirmed that the field options can be retrieved via the API, I close this issue.
